language: python
python:
  - "3.6"
install:
  - "pip install -r requirements.txt"
  - "pip install coverage"
  - "pip install coveralls"
# command to run tests
script: 
  - nosetests --source-package=app --with-coverage
after_success:
  coveralls